gemini:
  api_key:
  # - AIzaSyBtICg_bcc6r24rmFCMmZbYsO3rp5h6RBc
  - AIzaSyA-PF1FGGs3eudHXxbmRVk1c1GLa-vegJM
  - AIzaSyB_ksJ_2a2-Dg_rMtOTfa8h2SQwSXN4mbU
openrouter:
  api_key:
  - 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
hdfs_subpath:
  data_processed: /path/to/save/data_processed.parquet
  final_data: /path/to/save/final_data.parquet
  url_contents: /path/to/save/url_contents.parquet
hdfs:
  data_processed: ''
  final_data: ''
  url_contents: ''
hdfs_base_path: hdfs://hadoop-namenode:9000
langflow:
  api_url: http://192.168.50.90:7860
  flow_id:
    final_process: 80832dc6-c32a-4bb2-bbf2-685a39b7b360
    gen_columns_name: f7e665d3-6b5a-4292-864b-3c475dbdaaa7
    gen_query: 7404c63e-fa44-4e41-89ca-c152f86a4533
    process_data: 58c6612a-cf38-48b2-9fa7-e091589f4d91
  flow_json:
    final_process:
      name: AutoGenPandasProcess.json
      tweaks:
        api_key:
          id: GoogleGenerativeAIModel-VYuyQ
          key: google_api_key
          value: ''
    gen_columns_name:
      name: GenColumnsName.json
      tweaks:
        api_key:
          id: GoogleGenerativeAIModel-QsO4D
          key: google_api_key
          value: ''
    gen_query:
      name: AutoGenQuery.json
      tweaks:
        api_key:
          id: GoogleGenerativeAIModel-Mwrq9
          key: google_api_key
          value: ''
    process_data:
      name: SparkLLM.json
      tweaks:
        api_key:
          id: OpenRouterComponent-0mvLJ
          key: api_key
          value: ''
run_api_langflow: false
serper:
  api_key:
  - 1c7595865eba921adf8566ff53ca4219a862977e
  - 796a7c50b3630db0d654622b969d96e31b4289b9
spark:
  app_name: spark-collect-data
  master: spark://spark-master:7077
